# Generated by Django 6.0.1 on 2026-03-15 14:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ImportBatch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('source_file', models.CharField(blank=True, max_length=500)),
                ('import_type', models.CharField(db_index=True, max_length=100)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('validated', 'Validated'), ('completed', 'Completed'), ('failed', 'Failed')], db_index=True, default='pending', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('notes', models.TextField(blank=True)),
                ('success_count', models.PositiveIntegerField(default=0)),
                ('error_count', models.PositiveIntegerField(default=0)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='MetadataVariable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=100, unique=True)),
                ('value_type', models.CharField(choices=[('float', 'Float'), ('int', 'Integer'), ('text', 'Text'), ('bool', 'Boolean')], max_length=10)),
                ('display_name', models.CharField(blank=True, max_length=255)),
                ('is_filterable', models.BooleanField(default=False)),
            ],
            options={
                'ordering': ['display_name', 'name'],
            },
        ),
        migrations.CreateModel(
            name='Organism',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('scientific_name', models.CharField(db_index=True, max_length=255)),
                ('rank', models.CharField(max_length=64)),
                ('ncbi_taxonomy_id', models.PositiveIntegerField(blank=True, null=True)),
                ('notes', models.TextField(blank=True)),
            ],
            options={
                'ordering': ['scientific_name'],
                'constraints': [models.UniqueConstraint(condition=models.Q(('ncbi_taxonomy_id__isnull', False)), fields=('ncbi_taxonomy_id',), name='organism_unique_ncbi_taxonomy_id_when_present')],
            },
        ),
        migrations.CreateModel(
            name='Study',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('doi', models.CharField(blank=True, max_length=255, null=True)),
                ('title', models.CharField(max_length=500)),
                ('journal', models.CharField(blank=True, max_length=255)),
                ('year', models.PositiveIntegerField(blank=True, db_index=True, null=True)),
                ('country', models.CharField(blank=True, max_length=255)),
                ('notes', models.TextField(blank=True)),
            ],
            options={
                'ordering': ['title'],
                'constraints': [models.UniqueConstraint(condition=models.Q(('doi__isnull', False), models.Q(('doi', ''), _negated=True)), fields=('doi',), name='study_unique_doi_when_present')],
            },
        ),
        migrations.CreateModel(
            name='Group',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=255)),
                ('condition', models.CharField(blank=True, max_length=255)),
                ('sample_size', models.PositiveIntegerField(blank=True, null=True)),
                ('cohort', models.CharField(blank=True, max_length=255)),
                ('site', models.CharField(blank=True, max_length=255)),
                ('notes', models.TextField(blank=True)),
                ('study', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='groups', to='database.study')),
            ],
            options={
                'ordering': ['study__title', 'name'],
            },
        ),
        migrations.CreateModel(
            name='Comparison',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('label', models.CharField(max_length=255)),
                ('notes', models.TextField(blank=True)),
                ('group_a', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comparisons_as_a', to='database.group')),
                ('group_b', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comparisons_as_b', to='database.group')),
                ('study', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comparisons', to='database.study')),
            ],
            options={
                'ordering': ['study__title', 'label'],
            },
        ),
        migrations.CreateModel(
            name='BetaMetric',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('metric', models.CharField(max_length=100)),
                ('value', models.FloatField()),
                ('source', models.CharField(max_length=255)),
                ('notes', models.TextField(blank=True)),
                ('comparison', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='beta_metrics', to='database.comparison')),
                ('import_batch', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='beta_metrics', to='database.importbatch')),
            ],
            options={
                'ordering': ['comparison__study__title', 'comparison__label', 'metric'],
                'constraints': [models.UniqueConstraint(fields=('comparison', 'metric', 'source'), name='beta_metric_unique_comparison_metric_source')],
            },
        ),
        migrations.CreateModel(
            name='AlphaMetric',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('metric', models.CharField(max_length=100)),
                ('value', models.FloatField()),
                ('source', models.CharField(max_length=255)),
                ('notes', models.TextField(blank=True)),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='alpha_metrics', to='database.group')),
                ('import_batch', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='alpha_metrics', to='database.importbatch')),
            ],
            options={
                'ordering': ['group__study__title', 'group__name', 'metric'],
                'constraints': [models.UniqueConstraint(fields=('group', 'metric', 'source'), name='alpha_metric_unique_group_metric_source')],
            },
        ),
        migrations.CreateModel(
            name='MetadataValue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('value_text', models.TextField(blank=True, null=True)),
                ('value_float', models.FloatField(blank=True, null=True)),
                ('value_int', models.IntegerField(blank=True, null=True)),
                ('value_bool', models.BooleanField(blank=True, null=True)),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='metadata_values', to='database.group')),
                ('variable', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='metadata_values', to='database.metadatavariable')),
            ],
            options={
                'ordering': ['group__study__title', 'group__name', 'variable__name'],
                'constraints': [models.UniqueConstraint(fields=('group', 'variable'), name='metadata_value_unique_group_variable'), models.CheckConstraint(condition=models.Q(models.Q(('value_bool__isnull', True), ('value_float__isnull', False), ('value_int__isnull', True), ('value_text__isnull', True)), models.Q(('value_bool__isnull', True), ('value_float__isnull', True), ('value_int__isnull', False), ('value_text__isnull', True)), models.Q(('value_bool__isnull', True), ('value_float__isnull', True), ('value_int__isnull', True), ('value_text__isnull', False)), models.Q(('value_bool__isnull', False), ('value_float__isnull', True), ('value_int__isnull', True), ('value_text__isnull', True)), _connector='OR'), name='metadata_value_exactly_one_typed_value')],
            },
        ),
        migrations.CreateModel(
            name='QualitativeFinding',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('direction', models.CharField(choices=[('enriched', 'Enriched'), ('depleted', 'Depleted'), ('increased', 'Increased'), ('decreased', 'Decreased')], max_length=20)),
                ('source', models.CharField(max_length=255)),
                ('notes', models.TextField(blank=True)),
                ('comparison', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='qualitative_findings', to='database.comparison')),
                ('import_batch', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='qualitative_findings', to='database.importbatch')),
                ('organism', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='qualitative_findings', to='database.organism')),
            ],
            options={
                'ordering': ['comparison__study__title', 'comparison__label', 'organism__scientific_name'],
                'constraints': [models.UniqueConstraint(fields=('comparison', 'organism', 'direction', 'source'), name='qualitative_finding_unique_comparison_organism_direction_source')],
            },
        ),
        migrations.CreateModel(
            name='QuantitativeFinding',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('value_type', models.CharField(choices=[('relative_abundance', 'Relative abundance')], max_length=50)),
                ('value', models.FloatField()),
                ('unit', models.CharField(blank=True, max_length=50)),
                ('source', models.CharField(max_length=255)),
                ('notes', models.TextField(blank=True)),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='quantitative_findings', to='database.group')),
                ('import_batch', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='quantitative_findings', to='database.importbatch')),
                ('organism', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='quantitative_findings', to='database.organism')),
            ],
            options={
                'ordering': ['group__study__title', 'group__name', 'organism__scientific_name'],
                'constraints': [models.UniqueConstraint(fields=('group', 'organism', 'value_type', 'source'), name='quantitative_finding_unique_group_organism_type_source')],
            },
        ),
        migrations.AddConstraint(
            model_name='group',
            constraint=models.UniqueConstraint(fields=('study', 'name'), name='group_unique_study_name'),
        ),
        migrations.AddConstraint(
            model_name='comparison',
            constraint=models.UniqueConstraint(fields=('study', 'group_a', 'group_b', 'label'), name='comparison_unique_study_groups_label'),
        ),
        migrations.AddConstraint(
            model_name='comparison',
            constraint=models.CheckConstraint(condition=models.Q(('group_a', models.F('group_b')), _negated=True), name='comparison_distinct_groups'),
        ),
    ]
