# Generated by Django 6.0.1 on 2026-03-14 12:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Sample',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('label', models.CharField(max_length=255)),
                ('site', models.CharField(blank=True, max_length=255)),
                ('method', models.CharField(blank=True, max_length=255)),
                ('cohort', models.CharField(blank=True, max_length=255)),
                ('sample_size', models.PositiveIntegerField(blank=True, null=True)),
                ('notes', models.TextField(blank=True)),
            ],
            options={
                'ordering': ['study__title', 'label'],
            },
        ),
        migrations.CreateModel(
            name='ImportBatch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('source_file', models.CharField(blank=True, max_length=500)),
                ('import_type', models.CharField(max_length=100)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('notes', models.TextField(blank=True)),
                ('success_count', models.PositiveIntegerField(default=0)),
                ('error_count', models.PositiveIntegerField(default=0)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('validated', 'Validated'), ('completed', 'Completed'), ('failed', 'Failed')], default='pending', max_length=20)),
            ],
            options={
                'ordering': ['-uploaded_at'],
            },
        ),
        migrations.CreateModel(
            name='MetadataVariable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=100, unique=True)),
                ('display_name', models.CharField(max_length=255)),
                ('domain', models.CharField(blank=True, max_length=100)),
                ('value_type', models.CharField(choices=[('float', 'Float'), ('int', 'Integer'), ('text', 'Text'), ('bool', 'Boolean')], max_length=10)),
                ('default_unit', models.CharField(blank=True, max_length=50)),
                ('description', models.TextField(blank=True)),
                ('is_filterable', models.BooleanField(default=False)),
                ('allowed_values', models.JSONField(blank=True, default=list)),
            ],
            options={
                'ordering': ['display_name'],
            },
        ),
        migrations.CreateModel(
            name='CoreMetadata',
            fields=[
                ('sample', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='core_metadata', serialize=False, to='database.sample')),
                ('condition', models.CharField(blank=True, max_length=255)),
                ('male_percent', models.FloatField(blank=True, null=True)),
                ('age_mean', models.FloatField(blank=True, null=True)),
                ('age_sd', models.FloatField(blank=True, null=True)),
                ('bmi_mean', models.FloatField(blank=True, null=True)),
                ('bmi_sd', models.FloatField(blank=True, null=True)),
                ('notes', models.TextField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='Organism',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ncbi_taxonomy_id', models.PositiveIntegerField(db_index=True, unique=True)),
                ('scientific_name', models.CharField(max_length=255)),
                ('taxonomic_rank', models.CharField(max_length=64)),
                ('genus', models.CharField(blank=True, max_length=255)),
                ('species', models.CharField(blank=True, max_length=255)),
                ('notes', models.TextField(blank=True)),
                ('parent_taxonomy', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='children', to='database.organism')),
            ],
            options={
                'ordering': ['scientific_name'],
            },
        ),
        migrations.CreateModel(
            name='Study',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('source_doi', models.CharField(blank=True, max_length=255, null=True)),
                ('title', models.CharField(max_length=500)),
                ('country', models.CharField(blank=True, max_length=255)),
                ('journal', models.CharField(blank=True, max_length=255)),
                ('publication_year', models.PositiveIntegerField(blank=True, null=True)),
                ('notes', models.TextField(blank=True)),
            ],
            options={
                'ordering': ['title'],
                'constraints': [models.UniqueConstraint(condition=models.Q(('source_doi__isnull', False), models.Q(('source_doi', ''), _negated=True)), fields=('source_doi',), name='study_unique_source_doi_when_present')],
            },
        ),
        migrations.AddField(
            model_name='sample',
            name='study',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='samples', to='database.study'),
        ),
        migrations.CreateModel(
            name='MetadataValue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value_float', models.FloatField(blank=True, null=True)),
                ('value_int', models.IntegerField(blank=True, null=True)),
                ('value_text', models.TextField(blank=True, null=True)),
                ('value_bool', models.BooleanField(blank=True, null=True)),
                ('unit', models.CharField(blank=True, max_length=50)),
                ('raw_value', models.CharField(blank=True, max_length=255)),
                ('variation', models.CharField(blank=True, max_length=255)),
                ('notes', models.TextField(blank=True)),
                ('import_batch', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='metadata_values', to='database.importbatch')),
                ('sample', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='metadata_values', to='database.sample')),
                ('variable', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='metadata_values', to='database.metadatavariable')),
            ],
            options={
                'ordering': ['sample', 'variable'],
                'constraints': [models.UniqueConstraint(fields=('sample', 'variable'), name='metadata_value_unique_sample_variable'), models.CheckConstraint(condition=models.Q(models.Q(('value_bool__isnull', True), ('value_float__isnull', False), ('value_int__isnull', True), ('value_text__isnull', True)), models.Q(('value_bool__isnull', True), ('value_float__isnull', True), ('value_int__isnull', False), ('value_text__isnull', True)), models.Q(('value_bool__isnull', True), ('value_float__isnull', True), ('value_int__isnull', True), ('value_text__isnull', False)), models.Q(('value_bool__isnull', False), ('value_float__isnull', True), ('value_int__isnull', True), ('value_text__isnull', True)), _connector='OR'), name='metadata_value_exactly_one_typed_value')],
            },
        ),
        migrations.CreateModel(
            name='RelativeAssociation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('association_type', models.CharField(max_length=100)),
                ('value', models.FloatField(blank=True, null=True)),
                ('sign', models.CharField(blank=True, choices=[('positive', 'Positive'), ('negative', 'Negative'), ('neutral', 'Neutral')], max_length=20)),
                ('p_value', models.FloatField(blank=True, null=True)),
                ('q_value', models.FloatField(blank=True, null=True)),
                ('method', models.CharField(blank=True, max_length=255)),
                ('confidence', models.FloatField(blank=True, null=True)),
                ('notes', models.TextField(blank=True)),
                ('import_batch', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='relative_associations', to='database.importbatch')),
                ('organism_1', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='relative_associations_as_first', to='database.organism')),
                ('organism_2', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='relative_associations_as_second', to='database.organism')),
                ('sample', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='relative_associations', to='database.sample')),
            ],
            options={
                'ordering': ['sample', 'organism_1', 'organism_2', 'association_type'],
                'constraints': [models.UniqueConstraint(fields=('sample', 'organism_1', 'organism_2', 'association_type'), name='relative_association_unique_sample_pair_type'), models.CheckConstraint(condition=models.Q(('organism_1__lt', models.F('organism_2'))), name='relative_association_canonical_organism_order')],
            },
        ),
        migrations.AddConstraint(
            model_name='sample',
            constraint=models.UniqueConstraint(fields=('study', 'label'), name='sample_unique_study_label'),
        ),
    ]
